"""init core tables

Revision ID: 356fee4ce9ab
Revises: 
Create Date: 2026-09-06 03:44:53.144235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356fee4ce9ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('COMPANY', 'POSITION', name='experiencelevel'), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('position_title', sa.String(length=300), nullable=True),
    sa.Column('project_name', sa.String(length=300), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['experience_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jd_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('extra_meta_raw', sa.Text(), nullable=True),
    sa.Column('parsed_meta', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'ANALYZED', 'TAILORED', 'APPLIED', name='jdstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slot', sa.Enum('LIGHT', 'HEAVY', name='modelslot'), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('keyring_ref', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot', name='uq_model_config_slot')
    )
    op.create_table('profile_basic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('target_title', sa.String(length=200), nullable=True),
    sa.Column('education', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('school', sa.String(length=200), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('current_location', sa.String(length=200), nullable=True),
    sa.Column('target_location', sa.String(length=200), nullable=True),
    sa.Column('work_authorization', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience_bullet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['experience_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=False),
    sa.Column('skill_fit_score', sa.Float(), nullable=False),
    sa.Column('hard_requirement_penalty', sa.Float(), nullable=False),
    sa.Column('flexible_adjustment', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=200), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['jd_id'], ['jd_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_bank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('ONBOARDING', 'APPLICATION', name='qasource'), nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['jd_id'], ['jd_record.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=False),
    sa.Column('k_value', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.String(length=100), nullable=False),
    sa.Column('resume_json', sa.JSON(), nullable=True),
    sa.Column('markdown_text', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['jd_id'], ['jd_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_version')
    op.drop_table('qa_bank')
    op.drop_table('match_score')
    op.drop_table('experience_bullet')
    op.drop_table('profile_basic')
    op.drop_table('model_config')
    op.drop_table('jd_record')
    op.drop_table('experience_entry')
    # ### end Alembic commands ###
