"""phase2 profile depth and claimed skill

Revision ID: 3eea4bce52ea
Revises: 356fee4ce9ab
Create Date: 2026-09-10 20:34:55.794489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eea4bce52ea'
down_revision: Union[str, None] = '356fee4ce9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claimed_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_name', sa.String(length=200), nullable=False),
    sa.Column('experience_entry_id', sa.Integer(), nullable=False),
    sa.Column('action_summary', sa.Text(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source_jd_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_entry_id'], ['experience_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_jd_id'], ['jd_record.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('experience_bullet', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('experience_bullet', sa.Column('action_summary', sa.Text(), nullable=True))
    op.add_column('experience_bullet', sa.Column('result_summary', sa.Text(), nullable=True))
    op.add_column('experience_entry', sa.Column('background_notes', sa.Text(), nullable=True))
    op.add_column('experience_entry', sa.Column('background_qa', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience_entry', 'background_qa')
    op.drop_column('experience_entry', 'background_notes')
    op.drop_column('experience_bullet', 'result_summary')
    op.drop_column('experience_bullet', 'action_summary')
    op.drop_column('experience_bullet', 'keywords')
    op.drop_table('claimed_skill')
    # ### end Alembic commands ###
