"""phase6 md resume template and static profile sections

Revision ID: 7524cc414385
Revises: 58f037add887
Create Date: 2026-09-14 01:48:16.951457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7524cc414385'
down_revision: Union[str, None] = '58f037add887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school', sa.String(length=300), nullable=True),
    sa.Column('degree', sa.String(length=300), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=300), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_project_bullet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['personal_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('profile_basic', sa.Column('resume_summary', sa.Text(), nullable=True))
    op.add_column('profile_basic', sa.Column('skills_text', sa.Text(), nullable=True))
    # SQLite 不支持直接 ALTER TABLE ADD CONSTRAINT，新增外键列必须走 batch 模式
    # （拷贝重建表）——见 alembic 报错提示，其它几处 add_column（不带外键）
    # 不受影响，不需要 batch。
    with op.batch_alter_table('resume_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_resume_version_resume_template_id',
            'resume_template',
            ['resume_template_id'],
            ['id'],
            ondelete='SET NULL',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_version', schema=None) as batch_op:
        batch_op.drop_constraint('fk_resume_version_resume_template_id', type_='foreignkey')
        batch_op.drop_column('resume_template_id')
    op.drop_column('profile_basic', 'skills_text')
    op.drop_column('profile_basic', 'resume_summary')
    op.drop_table('personal_project_bullet')
    op.drop_table('resume_template')
    op.drop_table('personal_project')
    op.drop_table('education_entry')
    # ### end Alembic commands ###
